allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = "../build"
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}


// This subprojects block is only for this example's backwards compatibility.
// Older fuw plugin versions (2022.2.1 or earlier) don't have a `namespace` or 'kotlinOptions' property, which will throw errors.
// This block overrides these settings in the plugin's build.gradle.
subprojects {
    // make sure this is above any use of "evaluationDependsOn" 
    afterEvaluate {

        if (project.plugins.hasPlugin("com.android.application")
                || project.plugins.hasPlugin("com.android.library")) {

            // Fix for gallery_saver and other plugins missing namespace
            if (project.android.namespace == null) {
                // Try to get namespace from AndroidManifest.xml package attribute
                def manifestFile = file("${project.projectDir}/src/main/AndroidManifest.xml")
                if (manifestFile.exists()) {
                    def manifestContent = manifestFile.getText()
                    def packageMatch = manifestContent =~ /package=["']([^"']+)["']/
                    if (packageMatch.find()) {
                        project.android.namespace = packageMatch.group(1)
                    }
                }
                
                // If still null, set default namespaces for known plugins
                if (project.android.namespace == null) {
                    switch (project.name) {
                        case "gallery_saver":
                            project.android.namespace = "gallery_saver"
                            break
                        default:
                            // Try to infer from project name
                            project.android.namespace = project.name.replaceAll("-", "_")
                            break
                    }
                }
            }
            
            // Fix JVM target compatibility - ensure Java and Kotlin use the same target
            if (project.hasProperty("android")) {
                try {
                    // Set Java compile options to JVM 21 to match Kotlin
                    project.android.compileOptions {
                        sourceCompatibility = JavaVersion.VERSION_21
                        targetCompatibility = JavaVersion.VERSION_21
                    }
                    
                    // Set Kotlin JVM target to 21 to match Java
                    if (project.plugins.hasPlugin("org.jetbrains.kotlin.android")) {
                        project.android.kotlinOptions {
                            jvmTarget = "21"
                        }
                    }
                } catch (Exception e) {
                    // Ignore if configuration fails
                }
            }
        }
    }
}

subprojects {
    project.evaluationDependsOn(":app")
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
